### ISSUE TITLE
SearchField component

### ISSUE THREAD

**Issue by Lisa18289** [mittwald/flow#312]

**Comment by mfal** [comment]
@Lisa18289 could you also update the search field of the List component, when this component is ready? 🙏

**Comment by Jan-Eimertenbrink** [comment]
## Small retrospective Doc for the SearchField 

### Enter as submit

For several reasons, we initially decided to use Enter as a confirmation for the search:

- Familiar user behavior: Enter triggers the search.
- We generally follow [Spectrum (React Aria)](https://spectrum.adobe.com/page/search-field/#Keyboard-interactions), which also starts the search with Enter.

### Results only after submit

We deliberately decided against changing the content of the list while typing in the search, because:

- Users with short attention spans could be distracted by constantly changing content.
- The backend would quickly be overwhelmed if a request was sent after every typed letter.

However, we can imagine providing a type-ahead search in the future as part of further search expansion, but we don't see a current need for it.
