### ISSUE TITLE
Add option to add a button to a list component

### ISSUE THREAD

**Issue by JLampeMW** [mittwald/flow#651]
I would like it to be possible to integrate a button into the list component as in the example image.

![Bildschirmfoto 2024-08-23 um 15 16 03](https://github.com/user-attachments/assets/70c5d7ed-20cd-46dd-9bd7-914babea331b)

**Comment by Lisa18289** [comment]
Das ist bereits möglich, hier ein Beispiel:

```
     <ListItemView>
      <Heading>meine-domain.de</Heading>
      <Text>1AB59G51114</Text>

      <Button
        variant="plain"
        onPress={item.remove}
      >
        <IconClose />
      </Button>
    </ListItemView>
```

**Comment by Jan-Eimertenbrink** [comment]
During a discussion, we came up with the idea to use the [actions in a section](https://mittwald.github.io/flow/03-components/structure/section) for adding list elements, instead of providing a separate row with a button. Therefore, I would like to close this issue for now.

![Image](https://github.com/user-attachments/assets/b9dca676-4d43-41e2-8edc-913ad2839289)
