### ISSUE TITLE
CodeBlock: Placement of the Copy Button

### ISSUE THREAD

**Issue by Lisa18289** [mittwald/flow#897]
## Problem 
Currently, the copy button in the CodeBlock is always placed at the top right corner. If you need to scroll within the CodeBlock, the button only becomes visible once you scroll all the way to the right.

Example:
![Image](https://github.com/user-attachments/assets/a32fe9ef-2dd7-460f-9abd-f879ffefb02f)
![Image](https://github.com/user-attachments/assets/5bae8347-46ee-4e34-b127-2e181a315ffe)

**Comment by Nickzlos** [comment]
### Problem
When the code in a `CodeBlock` is too long, the current overflow behavior pushes the `CopyButton` out of the visible area.
We don't want to adress this problem by wrapping the code, as this can disrupt readability, especially for error logs or similar long-form outputs.

### Proposed Solution
Position the `CopyButton` in a dedicated column that is always fixed to the right edge of the `CodeBlock`. This column should maintain the same paddings and design tokens as the first column for the line numbering, ensuring consistency in appearance and alignment.
The code keeps the same overflow and scroll behavior.

![Image](https://github.com/user-attachments/assets/7dfc8dd6-7561-4acf-8ec2-165bce3d4bf6)

### Rejected Alternatives
- CopyButton in soft-variant: This approach was discarded because it does not display well on both light and dark themes due to the transparent background.
- CopyButton in solid-variant: This draws too much attention, making the CopyButton overly prominent.
- CopyButton positioned in a row above the Code: This introduces excess whitespace, creating an unbalanced design.
- Position CopyButton differently: Alternative placements are not ideal, as users generally expect the CopyButton in the top-right corner within CodeBlock components.
