### ISSUE TITLE
List Component :: Can we modify the "no result" message

### ISSUE THREAD

**Issue by gskyarts** [mittwald/flow#906]
Hi,

is it possible to customize the "no result" message or provide different outputs for the list component? 

Currently, I get the message "Keine Suchergebnisse gefunden ... ", but in my case, this is not correct. I have no data to fill the list initially (from api) and the current "no results" message implies that a filter or search has been used.

It would be helpful if we could have the option to change this message manually or we can switch to different messages for different scenarios (e. g. no initial data, no result after filtering, error from server or call api, ....)

**Comment by Jan-Eimertenbrink** [comment]
Hey, 

Instead of displaying an empty list, you can replace it with an [IllustratedMessage](https://mittwald.github.io/flow/03-components/content/illustrated-message). We’re already doing this in our mStudio. The IllustratedMessage has the advantage of filling the available space effectively and, with the help of the CTA (Call to Action), prompts the user to create a first item.

You can also find this under “[List](https://mittwald.github.io/flow/03-components/structure/list)” and then “Guidelines,” in the “IllustratedMessage” section. We’re currently working on making documentation sections linkable, but here’s a screenshot of the section I mean:
![Image](https://github.com/user-attachments/assets/b2681f84-baec-4c3f-b32d-ac00aa02be92)

Best regards Jan

**Comment by gskyarts** [comment]
ok, is fine for me - thanks

**Comment by Jan-Eimertenbrink** [comment]
Thank you for your question!
